### ISSUE TITLE
Add Demo Image

### ISSUE THREAD

**Issue by LeNPaul** [LeNPaul/Lagrange#1]
![demo](https://cloud.githubusercontent.com/assets/8409329/21747617/7ef0e18e-d53a-11e6-8f90-8bb14b62ba20.jpg)

**Comment by lynn9388** [comment]
Why not close this issue?

**Comment by LeNPaul** [comment]
![portfolio images](https://user-images.githubusercontent.com/8409329/32411720-08127b88-c1b9-11e7-9ec2-f8844de63df2.jpg)

**Comment by LeNPaul** [comment]
![lagrange](https://user-images.githubusercontent.com/8409329/32631384-17107870-c56e-11e7-932f-deeb7c12e4db.png)
