### ISSUE TITLE
Specify how to get started asap in the readme

### ISSUE THREAD

**Issue by davidglavas** [LeNPaul/Lagrange#17]
Make the readme **more user friendly** (this will increase the amount of users for sure) by creating a **step by step guide** which specifies how to: 
- personalize the website
- get started as quickly as possible.

Example: how to set the social icons in the footer, which are already available, maybe how to add more of them...

**Comment by LeNPaul** [comment]
Thanks for the suggestion! 

I originally thought that just linking to the demo (which has everything you mentioned - although I'm working on improving the documentation) would be enough, but you bring up a good argument for also including something in the readme.

I plan on updating the documentation soon, and will definitely take this suggestion.

Thanks!
