### ISSUE TITLE
inlined math symbol/equation problem in some browsers/systems

### ISSUE THREAD

**Issue by leimao** [LeNPaul/Lagrange#19]
Hi,
I was checking the Lagrange demo website in my cell phone, windows system and linux system using different web browsers. I found that there might be some problems of showing the inlined math symbol/equations in some of the combinations of the system and web browser. Hope this could be fixed.
Thanks.
Lei

**Comment by LeNPaul** [comment]
Thanks for the heads up, looking into it right now!

**Comment by LeNPaul** [comment]
Could you please describe what issues you are experiencing?
