### ISSUE TITLE
RSS functions?

### ISSUE THREAD

**Issue by manifestoso** [LeNPaul/Lagrange#20]
@LeNPaul interested adding an Atom (RSS) feed function?

**Comment by LeNPaul** [comment]
Will do! Thanks for the suggestion

**Comment by Mauladen** [comment]
reat question. In short, Atom is a better format. Think of it like RSS 3.0. For more information, see [this discussion on why we chose Atom over RSS 2.0](https://github.com/jekyll/jekyll-rss-feed/issues/2).

**Comment by manifestoso** [comment]
@mauladen @lenpaul I agree, Atom is a preferred choise.

**Comment by LeNPaul** [comment]
Thanks for your patience, this feature should be added soon

**Comment by LeNPaul** [comment]
I added RSS 2.0 for now, but Atom should be on the way within the week.
