### ISSUE TITLE
Update to FontAwesome 5

### ISSUE THREAD

**Issue by brianclemens** [LeNPaul/Lagrange#39]
How does this point to FontAwesome?  I was trying to find the old reference and change it to point at FontAwesome 5 so I don't load two versions, but I can't find the original reference in the first place.

**Comment by LeNPaul** [comment]
Hey, thanks for the suggestion! The reference to FontAwesome can be found here: https://github.com/LeNPaul/Lagrange/blob/gh-pages/_includes/head.html. I'll update it to the most recent version and credit you for the suggestion int he documentation.
