### ISSUE TITLE
Feed symbol leads to 404 when clicked from blog post

### ISSUE THREAD

**Issue by leyhline** [LeNPaul/Lagrange#40]
When clicking on the feed symbol in the page's header or footer while reading a post one gets redirected to the 404 page.

That's because the feed is located at: 
https://lenpaul.github.io/Lagrange/feed.xml

But while reading a blog post this becomes:
https://lenpaul.github.io/Lagrange/journal/feed.xml
which obviously doesn't exist. 

I fixed this by changing ```settings.yml``` from
`- {icon: 'rss-square', link: 'feed.xml'}`
to
`- {icon: 'rss-square', link: '/feed.xml'}`

This only works because I run Lagrange directly under the root URL but for the [demo page](https://lenpaul.github.io/Lagrange/) this fix won't work because is will link to https://lenpaul.github.io/feed.xml which also doesn't exist.

**Comment by LeNPaul** [comment]
Thanks for the PR, I just merged it. Also love what you did with the `_includes/social-icons.html` file.

**Comment by leyhline** [comment]
Glad you liked it. I'm quite new to static site generators and especially Jekyll. Thanks for your great theme!
