### ISSUE TITLE
Instructions For Making User Github Pages Site Instead of Project Github Pages Site? 

### ISSUE THREAD

**Issue by vedantroy** [LeNPaul/Lagrange#48]
I'm trying to use this theme to make a github pages site with the url "vedantroy.github.io". The current instructions say:

>To start using Jekyll right away with GitHub Pages, fork the Lagrange repository on GitHub. From there, you can rename your repository to 'USERNAME.github.io', where 'USERNAME' is your GitHub username, and edit the settings.yml file in the _data folder to your liking. **Ensure that you have a branch named gh-pages**. Your website should be ready immediately at 'http://USERNAME.github.io'. Note: if you are hosting several sites under the same GitHub username, then you will have to use Project Pages instead of User Pages - just change the repository name to something other than 'http://USERNAME.github.io'.

However, the current Github pages documention says that for user sites, the files can only be published from the master branch. What should I do? 

>If your site is a User or Organization Page that has a repository named <username>.github.io or <orgname>.github.io , you cannot publish your site's source files from different locations. User and Organization Pages that have this type of repository name are only published from the master branch.

**Comment by LeNPaul** [comment]
Hi there! Does it still work if you use the` gh-pages` branch?

**Comment by vedantroy** [comment]
I didn't try. I just ended up using my master branch instead.

**Comment by LeNPaul** [comment]
Does it work okay?

**Comment by vedantroy** [comment]
Yes
