### ISSUE TITLE
Multiple instances of class attribute.

### ISSUE THREAD

**Issue by aritra24** [LeNPaul/Lagrange#54]
https://github.com/LeNPaul/Lagrange/blob/c1ec3cbdf823067e55866c000b65d449859e5c83/index.html#L26

the class attribute is defined twice which causes the paginator-button and paginator-active classes to not render.

**Comment by LeNPaul** [comment]
Thanks for finding that! I will merge your pull request after I have a quick look and credit you in the documentation. Cheers!
